language: c
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  # Classic Driver
  - compiler: clang
    env: TESTID='classic'
  - compiler: gcc
    env: TESTID='classic'
  # Image Driver
  - compiler: gcc
    env: TESTID='image'
    addons:
      apt_packages:
        - libnetcdf-dev
        - mpich2
before_install:
  - source ci/${TESTID}.travis
  - vic_before_install
install:
  - vic_install
script:
  - vic_script
after_success:
  - vic_after_success
after_failure:
  - vic_after_failure
