language: c
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  # Image Driver
  - compiler: gcc
    os: linux
    env: TESTID='image'
    addons:
      apt_packages:
        - libnetcdf-dev
        - netcdf-bin
        - netcdf-doc
        - gfortran
        - valgrind
        # open-mpi is built from source in image.travis
  # Image Driver with rvic-routing
  - compiler: gcc
    os: linux
    env: TESTID='image' EXTENSIONS='ROUT=rout_rvic'
    addons:
      apt_packages:
        - libnetcdf-dev
        - netcdf-bin
        - netcdf-doc
        - gfortran
        - valgrind
        # open-mpi is built from source in image.travis
before_install:
  - source ci/vic_install_utils
  - source ci/${TESTID}.travis
  - install_miniconda
  - vic_before_install
install:
  - vic_install ${ROUT}
before_script:
  - vic_before_script
script:
  - vic_script
after_success:
  - vic_after_success
after_failure:
  - vic_after_failure
