language: c
sudo: false # use container based build
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - compiler: clang
    env:
    - DRIVER="classic"
    - INSTALL="make full -C vic/drivers/classic"
    - SCRIPT="./vic/drivers/classic/vic_classic.exe -o"
  - compiler: gcc
    env:
    - DRIVER="classic"
    - INSTALL="make full -C vic/drivers/classic"
    - SCRIPT="./vic/drivers/classic/vic_classic.exe -o"
  - compiler: gcc
    env:
    - DRIVER="image"
    addons:
      apt_packages:
        - libnetcdf-dev
        - mpich2
    - INSTALL="make full -C vic/drivers/image"
    - SCRIPT="./vic/drivers/image/vic_image.exe -o"
install:
  - echo $INSTALL; eval $INSTALL
script:
  - echo $SCRIPT; eval $SCRIPT
