language: c
compiler: gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libnetcdf-dev
    - sudo apt-get install -y mpich2
script:
    - make full -C drivers/classic/
    - make full -C drivers/image/
