site_name: VIC
site_description: Variable Infiltration Capacity Model
site_author: UW Hydro | Computational Hydrology
repo_url: https://github.com/UW-Hydro/VIC
site_url: http://vic.readthedocs.org/
theme: readthedocs
theme_dir: 'docs/custom_rtd_theme'
site_favicon: vic_favicon.jpg
copyright: 2015
docs_dir: docs
site_dir: site
use_directory_urls: true

# TODO:
# Pages: creating a hydrograph, plotting, miscellaneous
# figures
# links
# cant figure out how to hide pages
# decom WIKI
# two basin deliniation pages?
pages:
# Main pages
- Home: 'index.md'
- About:
    - 'Model Overview': 'Overview/ModelOverview.md'
    - 'References': 'Documentation/references.md'
    - 'FAQ': 'FAQ/FAQ.md'
    - 'Contact': 'contact.md'
- Documentation:
    - 'User Guide': 'Documentation/UserGuide.md'
    - VIC:
        - 'Basin Delineation': 'Documentation/BasinDelineation.md'
        - 'Inputs': 'Documentation/Inputs.md'
        - 'VIC Modes of Operation': 'Documentation/TechnicalNotes.md'
        - 'Running VIC': 'Documentation/RunVIC.md'
        - 'VIC Output Files': 'Documentation/Outputs.md'
        - 'Post-processing': 'Documentation/PostProcessing.md'
    - Routing:
        - 'Routing Input': 'Documentation/Routing/RoutingInput.md'
        - 'Run Routing': 'Documentation/Routing/RunRouting.md'
        - 'Routing Output': 'Documentation/Routing/RoutingOutput.md'
    - 'Plotting': 'Documentation/Plotting.md'
    - 'Calibration': 'Documentation/Calibration.md'
    - 'VIC Disagg': 'Documentation/VICDisagg.md'
- Development:
    - 'Development': 'Development/index.md'
    - 'Current Version': 'Development/CurrentVersion.md'
    - 'Archived Versions': 'Development/ArchivedVersions.md'
    - 'Version Summaries': 'Development/VersionSummaries.md'
    - 'Compatability': 'Development/CompatOpt.md'
    - 'Contributing': 'Development/Contributing.md'
    - 'Open Source': 'Development/open-source-philosophy.md'
    - 'Working with Git': 'Development/working-with-git.md'
    - 'Git Workflow': 'Development/git-workflow.md'
- Downloads:
    - Datasets: 'Datasets/Datasets.md'
    - Code: 'SourceCode/Code.md'
- hidden:
    - 'Forcing Data': 'Documentation/ForcingData.md'
    - 'Global Param': 'Documentation/GlobalParam.md'
    - 'Lake Param': 'Documentation/LakeParam.md'
    - 'Snow Band': 'Documentation/SnowBand.md'
    - 'Soil Param': 'Documentation/SoilParam.md'
    - 'State File': 'Documentation/StateFile.md'
    - 'Station Location': 'Documentation/StationLocation.md'
    - 'Veg Lib': 'Documentation/VegLib.md'
    - 'Veg Param': 'Documentation/VegParam.md'
    - 'Definitions': 'Documentation/definitions.md'
    - 'Soiltext': 'Documentation/soiltext.md'

markdown_extensions:
    - toc:
        permalink: True

copyright: 'Copyright &copy; 2015, <a href="http://uw-hydro.github.io/">University of Washington Computational Hydrology Group</a>.'
